[phases.setup]
nixPkgs = ["nodejs", "php82", "php82Extensions.pdo_pgsql"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install", "composer install"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build", "php artisan optimize:clear"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"